<a href="https://colab.research.google.com/github/benardwauye69-prog/Intro-to-Python-/blob/main/Introduction_to_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#just printing Hello World
#inline comments or single line comments
#will print out my name
#multi line or doc strings (single line comments)
"""
this line prints hello world
welcome to soft tec
my name is Benard
"""

print("Hello World")

Hello World

In [ ]:
print("my name is Benard Wauye") #shift + enter to execute a cell (inline comment)

my name is Benard Wauye

In [ ]:
#to add another cell
#esc + b

In [ ]:
def my_name():
  """
  I just want to print my name
  """
  my_name = "Benard Wauye"
  print(my_name)
  return 0

In [ ]:
# variables and data types

In [ ]:
# datatypes - it just defines the type of data a variable

In [ ]:
#string - used for anything text and appears inside quotes
print("hello world")

In [ ]:
#variable - name container that holds a value

In [ ]:
print("hello world")

In [ ]:
greeting = "hello world"
print(greeting)

hello world

In [ ]:
#total_price, unit_price, first_name

In [ ]:
#int --integer ..... whole numbers
12, 30, 50,50, 60
age = 40

In [ ]:
age = '40'
print(age)

40

In [ ]:
print(type(age))

<class 'str'>

In [ ]:
#addition
a = 30
b = 40
answer= a + b
print(answer)

70

In [ ]:
#float
temperature = 45.56
print(temperature)

45.56

In [ ]:
print(type(temperature)) #ctrl + a, ctrl + c, ctrl +v

<class 'float'>

In [ ]:
#boolean or bool,,,, this is a yes or no,,, true or false

In [ ]:
is_student = True

In [ ]:
print(type(is_student))

<class 'bool'>

In [ ]:
#**variabe** store for data
#**data type**  determines which data a variable can hold and in turn which
#types of data types
#string- should always be in quotes
#int - whole number
#float- decimal numbers
#bool- true or false
#use type() to check what kind of data a variable holds

In [ ]:
#build a simple calculator that does
#addition, subtraction, multiplication, division

a = int(input("Enter a number a "))
b = int(input("Enter a number b "))

#addition
result_add = a + b
print(f"Addition: {a} + {b} = {result_add}")

#subtraction
result_sub = a - b
print(f"Subtraction: {a} - {b} = {result_sub}")

#multiplication
result_multiply = a * b
print(f"Multiplication: {a} * {b} = {result_multiply}")

#division
if b != 0:
    result_div = a / b
    print(f"Division: {a} / {b} = {result_div}")
else:
    print("Error: Division by zero is not allowed.")

Enter a number a 10
Enter a number b 5
Addition: 10 + 5 = 15
Subtraction: 10 - 5 = 5
Multiplication: 10 * 5 = 50
Division: 10 / 5 = 2.0

In [ ]:
#type casting
#its changing the datattype of a variable from one form to another
#int-str

In [ ]:
#formatted string
#its the most modern and readable form of inserting a variable
first_name = "Benard" #this is the variable being inserted
#{} curly braces

print(f"hello my name is {first_name}") #variables ,, expressions

hello my name is Benard

In [ ]:
first_name = f"my name is Benard"
print(first_name)

my name is Benard

In [ ]:
last_name = str(input("please input your last name"))
age = int(input("please input your age"))

In [ ]:
#build a simple_interest calculator

In [ ]:
# Simple Interest Calculator
principal_str = input("Enter the principal amount: ")
principal = float(principal_str.replace(',', ''))

rate_str = input("Enter the annual interest rate (in percentage): ")
rate = float(rate_str.replace('%', ''))

time = float(input("Enter the time period (in years): "))

# Calculate simple interest
simple_interest = (principal * rate * time) / 100

print(f"The principal amount is: ${principal:.2f}")
print(f"The annual interest rate is: {rate:.2f}%")
print(f"The time period is: {time:.2f} years")
print(f"The simple interest is: ${simple_interest:.2f}")

Enter the principal amount: 450000
Enter the annual interest rate (in percentage): 17
Enter the time period (in years): 3
The principal amount is: $450000.00
The annual interest rate is: 17.00%
The time period is: 3.00 years
The simple interest is: $229500.00

In [ ]:
#simple calculator
a = int(input("Enter a number a"))
b = int(input("Enter a number b"))

#addition
is_result = a + b
print(is_result)

#subtraction
is_result = a - b
print(is_result)

#multiplication
is_result = a * b
print(is_result)

#division
is_result = a / b
print(is_result)

Enter a number a20
Enter a number b5
25
15
100
4.0

In [ ]:
#Simple Interest calculator

principal = float(input("Enter the principal amount:"))
rate = float(input("Enter the annual interest rate (in percentage): "))
time = float(input("Enter the time period in years"))

#Calculate simple interest
simple_interest = (principal * rate * time) / 100

#Display result
print(f"Simple Interest = {simple_interest}")

Enter the principal amount:450000
Enter the annual interest rate (in percentage): 17
Enter the time period in years3
Simple Interest = 229500.0

In [ ]:
#simple interest calculator by prof
_name = str(input("Enter your name:"))
p = int(input("Enter the principal amount:"))
r = int(input("Enter the annual interest rate (in percentage):"))
t = int(input("Enter the time period in years:"))

#calculate simple interest
simple_interest = (p * r * t) / 100

print(f(_name) , "your simple interest= {simple_interest}" )

In [ ]:
# Comparison and logical operators
#comparison operators show the relationship between two operands
# == equal to
# != not equal to
# >=
# <= less than or equal to
# > greater than
# < less than

In [ ]:
a = 50
b = 40
#==
print(a == b)

False

In [ ]:
a = 40
b = 30
#!=
print(a != b)

True

In [ ]:
a = 30
print( a >= 50)

False

In [ ]:
#operators in python
#addition, subtraction, multiplication, division, floor division, modulo or remainder, exponential(power)

#addition(numeric characters)
a = 30
b = 40
print(a+b)

70

In [ ]:
#concatenation
a = "strings"
b = "texts"
print(a+b)

stringstexts

In [ ]:
#subtraction (difference)
a = 30
b = 20
print(a-b)

10

In [ ]:
#multiplication(product)
a = 30
b = 20
print(a*b)

600

In [ ]:
#calculate the area of a piece of land(rectangular in shape)
l = 30
w = 40
area = l * w
print(area) #Python is case sensitive age = Age , Gender = gender

1200

In [ ]:
#division (quotient) -> numerical characters
a = 40
b = 20
print(a / b)
print(type(a/b))

2.0
<class 'float'>

In [ ]:
#floor division
#//
a = 40
b = 20
print(a//b)
print(type(a//b))

2
<class 'int'>

In [ ]:
#modulo or remainder -> %
a = 40
b = 20
print(a % b)
print(type(a % b))

0
<class 'int'>

In [ ]:
a = 7
b = 2
print(a % b)

1

In [ ]:
#exponential or power
a = 4
print(a**4)

256

In [ ]:
print(4*4*4*4)

256

In [ ]:
#logical operators
# are used to connect 2 or more boolean expressions or to invert a function
#and
#or
#not
# and - returns true if both expressions(statements) are true
a = 60
b = 60
print(a and b)

60

In [ ]:
#or - returns true if one of the expressions is true
#not - just inverts the expression

In [ ]:
#Control flow
#flow dictates the execution order of Python code base on conditions and loops
#conditional statements: if, else if, else

In [ ]:
#create a grading system for mathematics

score = int(input("enter your score"))
#88 - A
#78 - A-
#68 - B+
#58 - B-
#48 - C+

if score >= 88:
  print("The grade is A")
elif score >= 78:
  print("The grade is A-")
elif score >= 68:
  print("The grade is B+")
elif score >= 58:
  print("The grade is B-")
elif score >= 48:
  print("The grade is C+")

enter your score84
The grade is A-

In [ ]:
#create a system to show
#baby boomer genaplha genz millenial
age = int(input("Enter your age"))

if age <= 10:
  print("This is genalpha")
elif age <= 20:
  print("This is genz")
elif age <= 30:
  print("This is millenial")
elif age <= 40:
  print("This is a baby boomer")
else:
  print("The generation is undefined")

Enter your age28
This is millenial

In [ ]:
#create a 2027 election voting system
# age < 18 - they should not be allowed to take a voters card
#age >= 18 and they should have a national identity card they should
# otherwise they should not take a voters card

In [ ]:
# 2027 Voting System

print("=== 2027 Voting Registration System ===")

# Acquiring user's name
name = input("Enter your name: ")

# Acquiring user's age
age = int(input("Enter your age: "))

# Age below 18
if age < 18:
  print(name + ", you are NOT allowed to take a voters card")


# Age 18 or above
else:
  # Ask if the user has national ID

  national_id = input("Do you have a national ID? (yes/no): ")

  if national_id.lower() == "yes":
    print(name + ", you are allowed to take a voters card")
  else:
    print(name + ", you are NOT allowed to take a voters card because you do not have a national ID")

=== 2027 Voting Registration System ===
Enter your name: Benard Wauye
Enter your age: 28
Do you have a national ID? (yes/no): yes
Benard Wauye, you are allowed to take a voters card

In [ ]:
#for loop  in Python iterates over elements of a sequence like a list tuple

In [ ]:
#datastructures are used to store and organize collections of data efficiently
#lists []
#tuples()
#dictionaries {}
#sets {}

In [ ]:
#list
#the to do list
#the shopping list
 # list can hold data of any data type(float, string(text), int,)
fruits = ["banana", "mangoes", "apples", "tangarine"]
             #0          #1        #2        #3
#print(fruits[1])
 #print(fruits)
 #print(type(fruits))

 for 1 in fruits:
  print(1)

IndentationError: unexpected indent (782613611.py, line 11)

In [ ]:
#list
#shopping list -> soap, lotion, matchbox, unga
#a [] list could have data of any data type i.e str, int, float

shopping_list = ["Soap", "Unga", "Lotion", "Matchbox"]
                   #0       #1        #2          #3
# we can access elements of a list using index
#print(shopping_list) #printed the whole list

#print an item at any position using an index
#print(shopping_list[2]) #positive indexing

#can extract multiple elements from a list
print(shopping_list[1:2])
#what happened above is index slicing
#by retrieving a single item using its zero-based position

['Unga']

In [ ]:
#print the last item of the list
print(shopping_list[-1])

Matchbox

In [ ]:
#print the last item of the list
print(shopping_list[-2])

Lotion

In [ ]:
#sequences(mutable and immutable)
# mutable -> lists(list) & Byte Arrays (bytearray)
#immutable -> strings(str), tuples (tuple), Ranges(range), Bytes(bytes)

In [ ]:
#sequence [start:stop:step] is an ordered collection of items that can be accessed by their position(index)
#sequence is the list shopping_list[1:2]
#start: Index where the slice begins (incuded)
#stop: Index where the slice ends (exclude)
#step: Number of steps to skip between items
fruits = ["Dragon Fruit", "Mango", "Orange", "Banana"]
                 #0         #1        #2        #3
print(fruits[0:3])

['Dragon Fruit', 'Mango', 'Orange']

In [ ]:
# Full copy: nums [:] duplicates the entire sequence.
fruits = ["Dragon Fruit", "Mango", "Orange", "Banana"]
print(fruits[:])

In [ ]:
# Reversing: nums [::-1] flips the sequence to [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
fruits = ["Dragon Fruit", "Mango", "Orange", "Banana"]
print(fruits[::-1])

In [ ]:
# Negative Steps: nums [8:3:-2] counts backward to return [8, 6, 4] #you are going backwards 1,2,3,4 but then u decide to 4,3,2,1
fruits = ["Dragon Fruit", "Mango", "Orange", "Banana"]
print(fruits[3:0:-2]) #sequence[start:stop:step] i.e 1,2,3,4

my_numbers = [1, 2, 3, 4]
             #0 #1  #2  #3  #ascending or descending
             #ascending - smallest to largest -- we start with the lowest index(lowest value) 0
             #descending - largest to smallest -- we start with the largest index(highest value) 3

print(my_numbers[3:0:-2])

['Banana', 'Mango']
[4, 2]

In [ ]:
# add items on a list
# update
# delete
books = ["The River and The Source", "The River Between", "48 Laws of Power"]
print(books)

#append
books.append("Hey U Forgort Me")
print(books)

books.append("The Alchaemist")
print(books)

['The River and The Source', 'The River Between', '48 Laws of Power']
['The River and The Source', 'The River Between', '48 Laws of Power', 'Hey U Forgort Me']
['The River and The Source', 'The River Between', '48 Laws of Power', 'Hey U Forgort Me', 'The Alchaemist']

In [ ]:
# for loop
# to do list
to_do_list = ["Wash clothes", "Iron Clothes", "Go Shopping"]
print(to_do_list)

#print elements or items in their own line
#print items individually
# i is a variable name that represents the current item being processed from your to_do_list

for i in to_do_list:
  print(i)   #you can replace i with any word like (task)

['Wash clothes', 'Iron Clothes', 'Go Shopping']
Wash clothes
Iron Clothes
Go Shopping

In [ ]:
#tuple -> is a built in Python sequence used to store a collection of data.
#highly similar to a list but is IMMUTABLE
#once you create a tuple you cannot change, add or remove its elements

fruits = ("Banana", "Apple", "Mango")
print(fruits)
print(type(fruits))
#

('Banana', 'Apple', 'Mango')
<class 'tuple'>

In [ ]:
#assignment 1
#create a to do list with 5 different tasks
#add 3 more tasks
# update the task at index 3
# delete the task at index 2

In [ ]:
# assignment 1

to_do_list = ["Wake up", "Shower", "Make Bed", "Dress Up", "Eat Breakfast"]
                 #0        #1         #2          #3           #4
print(to_do_list)

#add 3 more tasks
to_do_list.append("Feed The Dog") #5
to_do_list.append("Wash The Car") #6
to_do_list.append("Read The Newspaper") #7
print(to_do_list)

#update the task at index 3
to_do_list[3] = "Wash Dishes"
print(to_do_list)

#delete the task at index 2
del to_do_list[2]
print(to_do_list)

['Wake up', 'Shower', 'Make Bed', 'Dress Up', 'Eat Breakfast']
['Wake up', 'Shower', 'Make Bed', 'Dress Up', 'Eat Breakfast', 'Feed The Dog', 'Wash The Car', 'Read The Newspaper']
['Wake up', 'Shower', 'Make Bed', 'Wash Dishes', 'Eat Breakfast', 'Feed The Dog', 'Wash The Car', 'Read The Newspaper']
['Wake up', 'Shower', 'Wash Dishes', 'Eat Breakfast', 'Feed The Dog', 'Wash The Car', 'Read The Newspaper']

In [ ]:
#Assignment 2
#create a fruits tuple
#perform indexing, slicing, loop

In [ ]:
# create a fruits tuple
fruits = ("Banana", "Apple", "Mango", "Orange", "Tangerine", "Pear")
       #    0          1        2         3           4          5

#indexing
print("First fruit:", fruits[0])
print("Third fruit:", fruits[2])
print("Last fruit:", fruits[-1])

#slicing
print("First three fruits:", fruits[0:3])
print("Middle fruits:", fruits[1:4])
print("Last two fruits:", fruits[-2:])

#looping through the tuple
print("All fruits in the tuple:")
for fruit in fruits:
  print(fruit)

First fruit: Banana
Third fruit: Mango
Last fruit: Pear
First three fruits: ('Banana', 'Apple', 'Mango')
Middle fruits: ('Apple', 'Mango', 'Orange')
Last two fruits: ('Tangerine', 'Pear')
All fruits in the tuple:
Banana
Apple
Mango
Orange
Tangerine
Pear

In [ ]:
#tuple ordered collection
#once it's been created it cannot be changed
#you cannot add any other item on it

In [ ]:
t = () #empty tuple
print(type(t))

<class 'tuple'>

In [ ]:
t = ("Apple", "Banana", "Cherry")

In [ ]:
#tuple without parenthesis(packing
coords = 10, 20
print(coords)
Print(type(coords))

(10, 20)

NameError: name 'Print' is not defined

In [ ]:
#accessing and upacking
t = ("a", "b", "c", "d", "e", "f")
#      1    2   3    4    5   6

#index or indices (0 based)
print(t[0])
print(t[1])
print(t[2])
print(t[3])
print(t[4])
print(t[5])

#unpacking
a, b, c, d, e, f = t

a
b
c
d
e
f

In [ ]:
#slicing
t = ("a", "b", "c", "d", "e", "f")
print(t[0:2])
print(t[3:5])

('a', 'b')
('d', 'e')

In [ ]:
#unpack
t = (1 , 2, 3, 4)
x, y, z, w = t
print(x)
print(y)
print(z)
print(w)

1
2
3
4

In [ ]:
#use a tuple when dealing with data that shouldnt change e.g coordinates, RCO values,

In [ ]:
t = (1 , 2, 2, 4)
#    0   1  2  3
t.count(2) #counting the occurences of an item in a tuple
t.index(2) #gives u the index of an item or the index of the first occurence of an item
len(t) #len stands for length or how many items there are in the tuple

#confirm4 is in the tuple
4 in t
3 in t

False

In [ ]:
#dictionary stores key value pairs
#values can be anything

In [ ]:
#creating and accessing item in a dictionary
person = {
    "name": "John", #keys should be in quotes either single or double
    "age": 30,
    "city": "Nairobi",
    "occupation": "Machine Learning Engineering",
    "Marital status": "Married"
}
print(type(person))
#list =["name", "age"]

<class 'dict'>

In [ ]:
#accessing items in dict
#person ["name"]
person.get("name")
person.get("age")

30

In [ ]:
#add item in the dict
for key in person:
  print(key, person[key])
for key, value in person.items():
  print(key)
for value in person.values():
  print(value)
for key, value in person.items():
  print(key, value

In [ ]:
#check if name exists in person(dict)
if "name" in person:
  print("Name exists in the dictionary")
else:
  print("Name does not exist in the dictionary")

Name exists in the dictionary

In [ ]:
#assigment 1

In [ ]:
data = {
    "user":{
        "name": "John",
        "age": 30,
        "city": "Nairobi",
        "occupation": "Machine Learning Engineering",
        "Marital status": "Married"
    }
}
data["user"]["name"]

'John'

In [ ]:
#always use .get{}instead of [] when the key might not exist. it wont crash your progress

In [ ]:
#assignment
#read on sets

In [ ]:
#Functions; fundamental building blocks in Python
#functions lets us reuse code.
#reusable blocks of code that execute function when called

In [ ]:
#write a fuunction to display greetings
def function_name():
  return None

In [ ]:
def greetings():
  return "Hello World" #return

In [ ]:
print(greetings())

Hello World

In [ ]:
def _calculator(a, b):
  result = a + b
  return result

In [ ]:
#calling the function
result = _calculator(2,4)
print(result)

6

In [ ]:
"""
Build a simple interest calculator
simple interest = (p * r * t)/100
global variable -> is accessed anywhere in the program
local variable -> is just accessed within the function
"""
p = 50000
r = 0.05
t = 2.5

def _simple_interest(p,r,t):
  p = 50000
  r = 5
  t = 2.5

  simple_interest = ((p * r * t)/100)
  return simple_interest

In [ ]:
#call the function
simple_interest = _simple_interest(p,r,t)
print(simple_interest)

6250.0

In [ ]:
#calculate area of a rectangle
#global variables
l = 30
w = 20
def _area_rectangle(l,w):
  area = l * w
  return area

In [ ]:
#local variables
def _area_rectangle():
  l = 30
  w = 20
  area = l * w
  return area

In [ ]:
area = _area_rectangle()
print(area)

600

In [ ]:
#The best way to write the function

def calculate_area(length, width):
  return length * width
#now you can reuse it for any size easily
room_area = calculate_area(30, 20) #returns 600
box_area = calculate_area(5, 10) #returns 50

In [ ]:
print(room_area)

600

In [ ]:
#build a simple data pipeline
#extract data from any source(csv fie,excel, json, html, avro, parquet,hdfs )-> transformation(remove duplicates, drop missing values or adding new columns(features)) feed it to a dashboard - use it for ml prediction
#ELT pipeline used for big data
#ETL pipelines(used for small scale data)

In [ ]:
#read on arrays in Python

In [ ]:
#pandas is excel in Python
# df -> data frame
# data frame ->table->has rows and columns

In [ ]:
import pandas as pd

In [ ]:
#!pip install pandas numpy scipy sqlalchemy
#install pandas using txt(requirements.txt)
#touch requirements.txt
#>>> pandas numpy tensorflow scipy

In [ ]:
import pandas as pd
print (pd.__version__)

2.2.2

In [72]:
#create a simple dataframe(sales data)
#Product, Quantity, Price, Customer_name
sales_data = {
    "Product":[
        "Laptop", "Mouse", "Laptop", "Keyboard",
        "Monitor", "Headphones", "Mouse",
        "Laptop", "USB Cable", "Phone Case",
        "Tablet", "Mouse", "Speaker",
        "Keyboard", "Charger"
    ],
    "Quantity":[
        2,3,4,None,
        1,5,2,
        1,10,4,
        3,3,2,
        1,6
    ],
    "Price":[
        50000,1200,50000,3000,
        25000,3500,1200,
        5200,500,None,
        30000,1200,7000,
        3000,1500

    ],
    "Customer Name":[
        "Victor", "Alice", "victor", "John",
        "Mary", "David", "James",
        "Grace", "Peter", "Brian",
        "Sarah", "Alice", "Daniel",
        "John", "Lucy"
    ]
}

#create DataFrame
df = pd.DataFrame(sales_data)

In [ ]:
#print five rows
df.head(3)

  Product  Quantity    Price Customer Name
0  Laptop       2.0  50000.0        Victor
1   Mouse       3.0   1200.0         Alice
2  Laptop       4.0  50000.0        victor

In [ ]:
#interacting with a database #cloud based database
#driver + dialect(what you use to connect to the database)
#postgresql://neondb_owner:npg_QYHE5DRlZ3Xq@ep-fragrant-scene-ab07tipb-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
#create a connection engine
#how to use environment variables in Python(to store secrets)

username = 'neondb_owner'
password = "npg_QYHE5DRlZ3Xq"
host = "ep-fragrant-scene-ab07tipb-pooler.eu-west-2.aws.neon.tech"
db = "neondb"
postgres_url = f"postgresql://{username}:{password}@{host}/{db}"
#this is an important credential(dont expose it)
#driver
#user(username)
#password
#host(where the database is hosted)
#database name

engine = create_engine(postgres_url)

In [75]:
#write the df to database
#read the data from the db
#Extraction(data ingestion) and Loading data
#E(db, files, datawarehouse)TL(db, datawarehouse,csv) OR ELT

#table(table name) #connection to the Engine
#replacing(U replace all the data in the table with new data)
#appending(U add new data to already existing data)
#updating
#if_exists checks whether the table exists and decides what to do with it
table_name = "sales_data"
df.to_sql(table_name, con=engine, if_exists="replace")

15

In [76]:
#read from the database
#GUI dbeaver
#table name, con
df = pd.read_sql_table("sales_data", con=engine)

In [77]:
df.head()

   index   Product  Quantity    Price Customer Name
0      0    Laptop       2.0  50000.0        Victor
1      1     Mouse       3.0   1200.0         Alice
2      2    Laptop       4.0  50000.0        victor
3      3  Keyboard       NaN   3000.0          John
4      4   Monitor       1.0  25000.0          Mary

In [ ]:
engine.connect()

In [ ]:
df.columns

Index(['Product', 'Quantity', 'Price', 'Customer Name'], dtype='object')

In [ ]:
df.dtypes

Product           object
Quantity         float64
Price            float64
Customer Name     object
dtype: object

In [ ]:
print(df.head()) #prints the first five rows #df.tail()

    Product  Quantity    Price Customer Name
0    Laptop       2.0  50000.0        Victor
1     Mouse       3.0   1200.0         Alice
2    Laptop       4.0  50000.0        victor
3  Keyboard       NaN   3000.0          John
4   Monitor       1.0  25000.0          Mary

In [ ]:
#save our sales df as a csv
df.to_csv('sales.csv', index=False)

#success message
print("sales.csv was successfully created")

sales.csv was successfully created

In [ ]:
!ls

sales.csv  sample_data

In [ ]:
#Data Analysis, BI analyst, data engineers, data scientist

def clean_sales_data(input_file, output_file):
  """
  read a sales csv file, cleans the data,
  performs transformation and it saves it into
  a new cleaned csv file
  """
  #read the csv file
  df = pd.read_csv(input_file)

  #print the original data
  print("Original data")
  print(df.head()) #shows the first 5 rows

  #clean column names
  #example Product nme -> product_name
  df.columns = (df.columns).str.strip().str.lower().str.replace(" ", "_") #removes extra space, converts to lowercase, and replaces spaces with

  #remove duplicates
  df = df.drop_duplicates()

  #remove rows with missing values
  important_columns = ["product", "quantity", "price"]
  df = df.dropna(subset=important_columns)

  #convert data types

  #ensure quantity and price are numbers
  df['quantity'] = pd.to_numeric(df['quantity'])
  df['price'] = pd.to_numeric(df['price'])

  #create a new column
  #total_sales = quantity * price
  df['total_sales'] = df['quantity'] * df['price']

  #save the cleaned and transformed data
  df.to_csv(output_file, index=False)

  print("Data cleaned successfully")
  print(f"Cleaned file saved as: {output_file}")

  #returned the cleaned df

  return df

In [ ]:
#sample usage
clean_sales_data("sales.csv","cleaned_sales.csv")

Original data
    Product  Quantity    Price Customer Name
0    Laptop       2.0  50000.0        Victor
1     Mouse       3.0   1200.0         Alice
2    Laptop       4.0  50000.0        victor
3  Keyboard       NaN   3000.0          John
4   Monitor       1.0  25000.0          Mary
Data cleaned successfully
Cleaned file saved as: cleaned_sales.csv

       product  quantity    price customer_name  total_sales
0       Laptop       2.0  50000.0        Victor     100000.0
1        Mouse       3.0   1200.0         Alice       3600.0
2       Laptop       4.0  50000.0        victor     200000.0
4      Monitor       1.0  25000.0          Mary      25000.0
5   Headphones       5.0   3500.0         David      17500.0
6        Mouse       2.0   1200.0         James       2400.0
7       Laptop       1.0   5200.0         Grace       5200.0
8    USB Cable      10.0    500.0         Peter       5000.0
10      Tablet       3.0  30000.0         Sarah      90000.0
12     Speaker       2.0   7000.0        Daniel      14000.0
13    Keyboard       1.0   3000.0          John       3000.0
14     Charger       6.0   1500.0          Lucy       9000.0

In [ ]:
!ls

cleaned_sales.csv  sales.csv  sample_data

In [ ]:
df = pd.read_csv("cleaned_sales.csv")
df.head()

      product  quantity    price customer_name  total_sales
0      Laptop       2.0  50000.0        Victor     100000.0
1       Mouse       3.0   1200.0         Alice       3600.0
2      Laptop       4.0  50000.0        victor     200000.0
3     Monitor       1.0  25000.0          Mary      25000.0
4  Headphones       5.0   3500.0         David      17500.0

In [ ]:
#error handling
#classes
#file handling
#a real world project(web application and we do data analytics and deploy our projects using docker)

In [ ]:
#code reusability(dry--dont repeat yourself)
#easier to debug(a data pipeline-transformation function)
#modularisation--
#

In [ ]:
#classes objects, methods, inheritance, polymorphism, encapsulation, constructors (Object oriented programming)

In [ ]:
#How to communicate to databases (relational databases - postgres,mssql,data warehouses)
#Production deployment - after building your application, you want it accessible to the necessary people(docker(devops-developer operations-after writing code what next))

In [ ]:
#write the df to the data base
# read the data from the db
#extraction and loading data
#E (db, files, datawarehouse) TL (db, datawarehouse, csv) OR
#table (table)


table_name = "sales_data"
df.to_sql(table_name, engine, if_exists="replace")

In [ ]:
df = pd._read_sql_table(table_name, engine)